apps/authentication/urls.py
from django.urls import path

from apps.authentication.views import (
    RegisterView,
    RegisterSuccessView,
    RegisterActivateEmailView,
)

app_name = "authentication"

urlpatterns = [
    path("registration/", RegisterView.as_view(), name="registration"),
    path(
        "registration-success/",
        RegisterSuccessView.as_view(),
        name="registration-success",
    ),
    path(
        "registration-activate/<str:token>/",
        RegisterActivateEmailView.as_view(),
        name="registration-activate",
    ),
]

apps/userlist/urls.py
from django.urls import path
from . import views

app_name = 'userlist'
urlpatterns = [
    path('', views.users, name='users'),
    path('user_detail/<int:pk>/', views.user_detail, name='user_detail'),
    path('user_delete/<int:pk>/', views.user_delete, name='user_delete'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include(("django.contrib.auth.urls", "accounts"), namespace="accounts")),
    path("authentication/", include("apps.authentication.urls", namespace="authentication")),
    path('', include('apps.userlist.urls')),
]

apps/authentication/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        email = self.normalize_email(email)
        email = email.lower()
        if not email:
            raise ValueError("The email must be set")
        user = User(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_("email"), unique=True)
    name = models.CharField(_("name"), max_length=255, blank=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)
    date_modified = models.DateTimeField(_("date modified"), auto_now=True)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"


def get_activation_token():
    return get_random_string(125)


class ActivationToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=125, default=get_activation_token)
    created_at = models.DateTimeField(auto_now_add=True)

apps/authentication/forms.py
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms
from django.db import transaction
from apps.authentication.models import ActivationToken
from .tasks import send_invitation_email

User = get_user_model()


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email", "name"]

    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    def clean_password2(self):
        if not self.data["password2"] == self.data["password"]:
            raise forms.ValidationError(_("Passwords mismatch"))

    def save(self, commit=True):
        user = super().save(commit=False)

        if commit:
            user.is_active = False
            user.set_password(self.data["password"])
            user.save()
            activation_token = ActivationToken.objects.create(user=user)
            transaction.on_commit(
                lambda: send_invitation_email.delay(activation_token.id)
            )
        return user

apps/authentication/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView
from apps.authentication.forms import RegistrationForm
from apps.authentication.models import ActivationToken

User = get_user_model()


class RegisterView(CreateView):
    model = User
    template_name = "registration/registration.html"
    success_url = reverse_lazy("authentication:registration-success")

    def get_form_class(self):
        return RegistrationForm


class RegisterSuccessView(TemplateView):
    template_name = "registration/registration-success.html"


class RegisterActivateEmailView(TemplateView):
    template_name = "registration/registration-activate.html"

    def get_context_data(self, **kwargs):
        token = self.kwargs.get("token")
        activation_token = get_object_or_404(ActivationToken, token=token)
        activation_token.user.is_active = True
        activation_token.user.save()
        activation_token.delete()

apps/userlist/views.py
from django.shortcuts import render
from apps.authentication.models import User


def users(request):
    return render(request, 'userlist/users.html', {
        'title': 'User List',
        'page_active': 'users',
        'users': User.objects.all().order_by("id"),
        'req_user': request.user,
    })


def user_detail(request, pk):
    user_detail = User.objects.filter(id=pk).first()
    id_not_found = True if user_detail is None else False
    return render(request, 'userlist/user_detail.html', {
        'title': 'User Detail',
        'page_active': 'users',
        'id_not_found': id_not_found,
        'pk': pk,
        'user_detail': user_detail,
        'req_user': request.user,
    })


def user_delete(request, pk):
    user_delete = User.objects.filter(id=pk).first()
    id_not_found = True if user_delete is None else False
    if not id_not_found:
        user_delete.delete()
    return render(request, 'userlist/user_delete.html', {
        'title': 'User Delete',
        'page_active': 'users',
        'id_not_found': id_not_found,
        'pk': pk,
        'user_delete': user_delete,
        'req_user': request.user,
    })

apps/userlist/templates/userlist/user_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    {% if id_not_found %}
        <p>User: {{ pk }} does not exist.</p>
    {% else %}

        The user has been deleted successfully.

        <ul class="pagination">
            <li class="page-item active"><a class="page-link" href="{% url 'userlist:users' %}">Main page</a></li>
        </ul>

    {% endif %}

{% endblock %}

apps/userlist/templates/userlist/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    {% if id_not_found %}
        <p>User: {{ pk }} does not exist.</p>
    {% else %}

        <ul class="pagination">
            <li class="page-item active"><a class="page-link" href="{% url 'userlist:users' %}">&laquo; Back</a></li>
        </ul>

        <div class="card mb-3" style="max-width: 540px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{% static 'userlist/img/no_image.png' %}" class="img-fluid rounded-start" width="100%" height="100%" alt="Photo_movie">
            </div>
            <div class="col-md-8">
              <div class="card-body" style="position: relative;">
                <b>{{ user_detail.name }}</b><br/>
                {{ user_detail.email }}<br/>
                {% if req_user.id == user_detail.id %}
                  <a href="{% url 'userlist:user_delete' user_detail.id %}"><img src="{% static 'userlist/img/icon_delete_auth_user.png' %}" width="32" height="32" alt="Delete_User"></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>

    {% endif %}

{% endblock %}

apps/userlist/templates/userlist/users.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block content %}

    {% if not users %}
        Users not found...
    {% else %}

        <div class="container">
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                {% for user in users %}
                    <div class="col">
                        <a class="user-list-item" href="{% url 'userlist:user_detail' user.id %}">

                          <div class="card shadow-sm">
                            <img src="{% static 'userlist/img/no_image.png' %}" width="100%" height="100%" alt="User_Photo">
                            <div class="card-body">
                                {% if req_user.id == user.id %}
                                    <a href="{% url 'userlist:user_delete' user.id %}"><img src="{% static 'userlist/img/icon_delete_auth_user.png' %}" width="32" height="32" alt="Delete_User"></a>
                                {% endif %}
                                <b>{{ user.name }}</b>
                            </div>

                          </div>

                        </a>
                    </div>
                {% endfor %}
          </div>
        </div>

    {% endif %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href=" {% static 'userlist/img/favicon.ico' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">

    <style>
        * {
            font-family: 'Raleway', sans-serif;
        }
        html {
            background-color: #fff;
        }
        body {
            background-color: #fff;
        }
        a.user-list-item, a.user-list-item:hover, a.user-list-item:visited {
            color: black;
            text-decoration: none;
        }
        .border-bottom {
            border-bottom: 1px solid #999!important;
        }
    </style>
</head>
<body>
    <header class="p-3 mb-3 border-bottom">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

            <a href="{% url 'userlist:users' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
              <!-- <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg> -->
              <img src="{% static 'userlist/img/logo_2bcode.png' %}">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <!-- <li><a href="{% url 'userlist:users' %}" class="nav-link px-2 {% if page_active == 'users' %} link-primary {% else %} link-dark {% endif %}">Users</a></li> -->
            </ul>

            <div class="dropdown text-end">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                {% if req_user.is_authenticated %}
                    <img src="{% static 'authentication/img/account.png' %}">{{ req_user.name }}
                {% else %}
                    Not logged in
                {% endif %}
              </a>
              <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                {% if req_user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'accounts:login' %}">Sign in</a></li>
                {% endif %}
              </ul>
            </div>

          </div>
        </div>
      </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>